name: Run pre-commit checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pre-commit:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    container:
      image: kasperskydh/knp-build-image
      volumes:
        - ${{ github.workspace }}:/KNP
      options: --cpus 1
    steps:
    - uses: actions/checkout@v3
    - id: changed_files
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ' '
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files ${{ steps.changed_files.outputs.files}}
